import type { Metadata } from "next";

import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
        <Header/>


        <div className="min-h-screen flex bg-grey-200">
          {/* Sidebar */}
          <Sidebar/>
          <div className = "flex-1 p-5  overflow-y-auto scrollbar-hide">
            {children}
          </div>
        </div>
       <Toaster 
          position="top-center" 
          expand={true}
          richColors
          closeButton
          theme="light"
        />
      </body>
    </html>
    </ClerkProvider>
  );
}
